# Generated by Django 3.2.9 on 2021-11-21 12:26

from django.db import migrations, models
import lista.models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listamodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=lista.models.upload_image),
        ),
    ]
