# Generated by Django 3.2.9 on 2021-11-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_listamodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listamodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
